version: 2
jobs:
  build:
    docker:
      - image: circleci/node:12.4
    working_directory: ~/repo
    steps:
      - checkout
      - run:
          name: Install dbus-dev package
          command: 'sudo apt-get install libdbus-glib-1-dev'
      - restore_cache:
          keys:
            - v1-dependencies-{{ checksum "package.json" }}
            - v1-dependencies-
      - run: yarn install
      - save_cache:
          paths:
            - node_modules
          key: v1-dependencies-{{ checksum "package.json" }}
      - run: cp src/config.sample.js src/config.js
      - run: yarn test
